<?php /** @var \Test\CustomerImage\Block\Customer\Account $block */ ?>
<fieldset class="fieldset create account" data-hasrequired="<?= __('* Required Fields') ?>">
    <legend class="legend">
        <span>
        <?= __('Logo') ?>
        </span>
    </legend>

    <div class="field customer_image ">
        <label for="customer_image" class="label"><span><?= __('Customer Image') ?></span></label>
        <div class="control">
            <?php if ($logo = $block->getFileUrl()): ?>
                <img src="<?php echo $logo ?>" alt="logo" height="400" width="400"/>
            <?php endif; ?>
            <input type="file" name="customer_image" id="customer_image" title="<?= __('Logo Image') ?>" class="input-text" data-validate="{required:false}">
        </div>
    </div>
</fieldset>
