<?php

/** @var Test\Countdown\Block\Product\CountDown $block */

?>

<?php if ($block->getFirstEndTime() != null): ?>
<div id="getting-started"></div>
    <script type="text/javascript">
        require([
            'jquery',
            'countdown'
        ], function (
            $, countdown
        ) {
            jQuery("#getting-started")
                .countdown("<?= $block->getFirstEndTime()?>", function(event) {
                    jQuery(this).text(
                        event.strftime('%D day`s %H hour`s %M minute`s %S second`s')
                    );
                });
        });
    </script>
<?php endif; ?>
