<?php
/**
 * @var Test\RequestPrice\Block\Product\RequestPrice $block
 */
?>
<div class="actions">
    <button type="button" class="btn btn-primary btn-lg" id="price-request-btn">Request Price</button>
</div>


<div id="modal-content" >
    <div class="modal-inner-content">
        <form class="form" id="custom-form" method="post" autocomplete="off" data-mage-init='{"validation":{}}'>
            <fieldset class="fieldset">
                <div class="field required">
                    <label for="name" class="label"><span><?php echo __('Name') ?></span></label>
                    <div class="control">
                        <input type="name" name="rp-name" id="rp-name" value="" title="<?php echo __('Name') ?>" class="input-text" data-validate="{required:true, 'validate-alpha':true}">
                    </div>
                </div>
                <div class="field required">
                    <label for="email_address" class="label"><span><?php echo __('Email') ?></span></label>
                    <div class="control">
                        <input type="email" name="rp-email" id="rp-email" value="" title="<?php echo __('Email') ?>" class="input-text" data-validate="{required:true, 'validate-email':true}">
                    </div>
                </div>
                <div class="field">
                    <label for="comment" class="label"><span><?php echo __('Comment') ?></span></label>
                    <div class="control">
                        <input type="text" name="rp-comment" id="rp-comment" value="" title="<?php echo __('Comment') ?>" class="input-text" data-validate="{required:false}">
                    </div>
                </div>
                <button id="submit-rq-price" type="submit" title="Submit" class="action primary">
                    <span>Submit</span>
                </button>
            </fieldset>
        </form>
    </div>
</div>

<script type="text/x-magento-init">
{
    "*": {
        "requestPrice": {
            "url":"<?php echo $block->getUrl('request_price/index/save'); ?>",
            "sku":"<?php echo $block->getProduct()->getSku(); ?>",
            "created":"<?php echo $block->getDate(); ?>"
        }
    }
}
</script>
