<?php
/**
 * @var Test\RequestPrice\Block\Product\RequestPrice $block
 */
?>
<div class="actions">
    <button type="button" class="btn btn-primary btn-lg" id="price-request-btn" data-toggle="modal"
            data-target="#modal-content">Request Price</button>
</div>


<div id="modal-content" >
    <div class="modal-inner-content">
        <form class="form" id="custom-form" method="post" autocomplete="off">
            <fieldset class="fieldset">
                <div class="field required">
                    <label for="name" class="label"><span><?php echo __('Name') ?></span></label>
                    <div class="control">
                        <input type="name" name="rp-name" id="rp-name" value="" title="<?php echo __('Name') ?>" class="input-text" data-validate="{required:true, 'validate-alpha':true}">
                    </div>
                </div>
                <div class="field required">
                    <label for="email_address" class="label"><span><?php echo __('Email') ?></span></label>
                    <div class="control">
                        <input type="email" name="rp-email" id="rp-email" value="" title="<?php echo __('Email') ?>" class="input-text" data-validate="{required:true, 'validate-email':true}">
                    </div>
                </div>
                <div class="field">
                    <label for="comment" class="label"><span><?php echo __('Comment') ?></span></label>
                    <div class="control">
                        <input type="text" name="rp-comment" id="rp-comment" value="" title="<?php echo __('Comment') ?>" class="input-text" data-validate="{required:false}">
                    </div>
                </div>
                <button id="submit_rq_price" type="submit" title="Submit" class="action submit primary">
                    <span>Submit</span>
                </button>
            </fieldset>
        </form>
    </div>
</div>

<!--
<script>
    require(['jquery', 'Test_RequestPrice/js/popup'],
        function ($) {
           return;
        }
    );
</script>
-->

<script>
    require(

        [
            'jquery',
            'Magento_Ui/js/modal/modal',
        ],
        function(
            $,
            modal
        ) {
            let url = "<?php echo $block->getUrl('request_price/index/save') ?>";
            let sku = "<?php echo $block->getProduct()->getSku() ?>";
            let created = "<?php echo $block->getDate(); ?>";

            let options = {
                type: 'popup',
                responsive: true,
                innerScroll: true,
                title: 'Request the price',
                buttons: [{
                    text: $.mage.__('Close'),
                    class: 'modal-close',
                    click: this.closeModal,
                }
                ]
            };

            function onsubmit(){
                jQuery.ajax({
                    url: url,
                    type: "POST",
                    data: {
                        name:$("#rp-name").val(),
                        email:$("#rp-email").val(),
                        comment:$("#rp-comment").val(),
                        sku:sku,
                        created_at:created,
                        status: 'New'
                    },
                    showLoader: true,
                });
            }

            $("#submit_rq_price").on('click',function(){
                onsubmit();

            });

            modal(options, $('#modal-content'));
            $("#price-request-btn").on('click',function(){
                $("#modal-content").modal("openModal");

            });
        }
    );
</script>
