<?php

$myBlock = \Magento\Framework\App\ObjectManager::getInstance()->get('Test\Get\Block\HelloWorld');

$currentProduct = $myBlock->getCurrentProduct();

if ($currentProduct = $myBlock->getCurrentProduct()) {
    $relatedProducts = $currentProduct->getRelatedProducts();

    if (!empty($relatedProducts)) {
        echo 'Related Products <br />';
        foreach ($relatedProducts as $relatedProduct) {
            echo $relatedProduct->getSku() . '<br />';
            echo $relatedProduct->getName(); //get name
            echo $relatedProduct->getPrice(); //get price
            #print_r($relatedProduct->getData()); //Show all attributes
        }
    }

    $upSellProducts = $currentProduct->getUpSellProducts();

    if (!empty($upSellProducts)) {
        echo '<h3>UpSell Products</h3>';
        foreach ($upSellProducts as $upSellProduct) {
            echo $upSellProduct->getSku() . '<br />';
        }
    }

    $crossSellProducts = $currentProduct->getCrossSellProducts();

    if (!empty($crossSellProduct)) {
        echo 'CrossSell Products <br />';
        foreach ($crossSellProducts as $crossSellProduct) {
            echo $crossSellProduct->getSku() . '<br />';
        }
    }

}
