<?php
$myBlock = \Magento\Framework\App\ObjectManager::getInstance()->get('Test\Get\Block\HelloWorld');


// print current product data
if ($currentProduct = $myBlock->getCurrentProduct()) {
    echo $currentProduct->getName() . '<br />';
    echo $currentProduct->getSku() . '<br />';
    echo $currentProduct->getFinalPrice() . '<br />';
    echo $currentProduct->getProductUrl() . '<br />';
    print_r ($currentProduct->getCategoryIds()) . '<br />';
}

// print current category data
if ($currentCategory = $myBlock->getCurrentCategory()) {
    echo $currentCategory->getName() . '<br />';
    echo $currentCategory->getUrl() . '<br />';
}
